cosmo_client_0:
  remote: null
  local: /nfs-share/datasets/photon/dataset_cache/smollm-corpus-shared/cosmo/client_0
  split: train
  proportion: 0.10
cosmo_client_1:
  remote: null
  local: /nfs-share/datasets/photon/dataset_cache/smollm-corpus-shared/cosmo/client_1
  split: train
  proportion: 0.10
cosmo_client_2:
  remote: null
  local: /nfs-share/datasets/photon/dataset_cache/smollm-corpus-shared/cosmo/client_2
  split: train
  proportion: 0.10
cosmo_client_3:
  remote: null
  local: /nfs-share/datasets/photon/dataset_cache/smollm-corpus-shared/cosmo/client_3
  split: train
  proportion: 0.10
cosmo_client_4:
  remote: null
  local: /nfs-share/datasets/photon/dataset_cache/smollm-corpus-shared/cosmo/client_4
  split: train
  proportion: 0.10
cosmo_client_5:
  remote: null
  local: /nfs-share/datasets/photon/dataset_cache/smollm-corpus-shared/cosmo/client_5
  split: train
  proportion: 0.10
cosmo_client_6:
  remote: null
  local: /nfs-share/datasets/photon/dataset_cache/smollm-corpus-shared/cosmo/client_6
  split: train
  proportion: 0.10
cosmo_client_7:
  remote: null
  local: /nfs-share/datasets/photon/dataset_cache/smollm-corpus-shared/cosmo/client_7
  split: train
  proportion: 0.10
cosmo_client_8:
  remote: null
  local: /nfs-share/datasets/photon/dataset_cache/smollm-corpus-shared/cosmo/client_8
  split: train
  proportion: 0.10
cosmo_client_9:
  remote: null
  local: /nfs-share/datasets/photon/dataset_cache/smollm-corpus-shared/cosmo/client_9
  split: train
  proportion: 0.10
cosmo_client_10:
  remote: null
  local: /nfs-share/datasets/photon/dataset_cache/smollm-corpus-shared/cosmo/client_10
  split: train
  proportion: 0.10
cosmo_client_11:
  remote: null
  local: /nfs-share/datasets/photon/dataset_cache/smollm-corpus-shared/cosmo/client_11
  split: train
  proportion: 0.10
cosmo_client_12:
  remote: null
  local: /nfs-share/datasets/photon/dataset_cache/smollm-corpus-shared/cosmo/client_12
  split: train
  proportion: 0.10
cosmo_client_13:
  remote: null
  local: /nfs-share/datasets/photon/dataset_cache/smollm-corpus-shared/cosmo/client_13
  split: train
  proportion: 0.10
cosmo_client_14:
  remote: null
  local: /nfs-share/datasets/photon/dataset_cache/smollm-corpus-shared/cosmo/client_14
  split: train
  proportion: 0.10
cosmo_client_15:
  remote: null
  local: /nfs-share/datasets/photon/dataset_cache/smollm-corpus-shared/cosmo/client_15
  split: train
  proportion: 0.10
