[project]
name = "dyna"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mosaicml[streaming, wandb]==0.32.1",
    "flash-attn==2.8.1",
    "matplotlib>=3.10.3",
    "tqdm>=4.67.1",
    "transformers>=4.51.0",
    "beartype>=0.21.0",
    "hydra-core>=1.3.2",
    "llm-foundry==0.22.0",
    "setuptools==80",
    "pyinstrument>=5.0.3",
    "pandas>=2.3.1",
    "seaborn>=0.13.2",
    "ipykernel>=6.30.0",
    "jaxtyping>=0.3.2",
    "triton>=3.3.0",
    "torchinfo>=1.8.0",
    "torch>=2.7.0",
]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["dyna"]

[tool.uv]
no-build-isolation-package = ["flash-attn"]
