[project]
name = "abbie"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mosaicml[streaming, wandb]==0.31.0",
    "flash-attn==2.8.1",
    "matplotlib>=3.10.3",
    "tqdm>=4.67.1",
    "transformers>=4.51.0",
    "beartype>=0.21.0",
    "hydra-core>=1.3.2",
    "llm-foundry==0.21.0"

]

[tool.uv]
no-build-isolation-package = ["flash-attn"]