[project]
name = "abbie"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mosaicml==0.32.0",
    "flash-attn==2.8.1",
    "matplotlib>=3.10.3",
    "tqdm>=4.67.1",
    "transformers>=4.53.2",
]

[tool.uv]
no-build-isolation-package = ["flash-attn"]
