python_edu_client_0:
  remote: s3://smollm-corpus/shared/python_edu/client_0
  local: /nfs-share/datasets/photon/dataset_cache/smollm-corpus-shared/python_edu/client_0
  split: train
  proportion: 0.10
python_edu_client_1:
  remote: s3://smollm-corpus/shared/python_edu/client_1
  local: /nfs-share/datasets/photon/dataset_cache/smollm-corpus-shared/python_edu/client_1
  split: train
  proportion: 0.10
python_edu_client_2:
  remote: s3://smollm-corpus/shared/python_edu/client_2
  local: /nfs-share/datasets/photon/dataset_cache/smollm-corpus-shared/python_edu/client_2
  split: train
  proportion: 0.10
python_edu_client_3:
  remote: s3://smollm-corpus/shared/python_edu/client_3
  local: /nfs-share/datasets/photon/dataset_cache/smollm-corpus-shared/python_edu/client_3
  split: train
  proportion: 0.10
python_edu_client_4:
  remote: s3://smollm-corpus/shared/python_edu/client_4
  local: /nfs-share/datasets/photon/dataset_cache/smollm-corpus-shared/python_edu/client_4
  split: train
  proportion: 0.10
python_edu_client_5:
  remote: s3://smollm-corpus/shared/python_edu/client_5
  local: /nfs-share/datasets/photon/dataset_cache/smollm-corpus-shared/python_edu/client_5
  split: train
  proportion: 0.10
python_edu_client_6:
  remote: s3://smollm-corpus/shared/python_edu/client_6
  local: /nfs-share/datasets/photon/dataset_cache/smollm-corpus-shared/python_edu/client_6
  split: train
  proportion: 0.10
python_edu_client_7:
  remote: s3://smollm-corpus/shared/python_edu/client_7
  local: /nfs-share/datasets/photon/dataset_cache/smollm-corpus-shared/python_edu/client_7
  split: train
  proportion: 0.10
python_edu_client_8:
  remote: s3://smollm-corpus/shared/python_edu/client_8
  local: /nfs-share/datasets/photon/dataset_cache/smollm-corpus-shared/python_edu/client_8
  split: train
  proportion: 0.10
python_edu_client_9:
  remote: s3://smollm-corpus/shared/python_edu/client_9
  local: /nfs-share/datasets/photon/dataset_cache/smollm-corpus-shared/python_edu/client_9
  split: train
  proportion: 0.10
python_edu_client_10:
  remote: s3://smollm-corpus/shared/python_edu/client_10
  local: /nfs-share/datasets/photon/dataset_cache/smollm-corpus-shared/python_edu/client_10
  split: train
  proportion: 0.10
python_edu_client_11:
  remote: s3://smollm-corpus/shared/python_edu/client_11
  local: /nfs-share/datasets/photon/dataset_cache/smollm-corpus-shared/python_edu/client_11
  split: train
  proportion: 0.10
python_edu_client_12:
  remote: s3://smollm-corpus/shared/python_edu/client_12
  local: /nfs-share/datasets/photon/dataset_cache/smollm-corpus-shared/python_edu/client_12
  split: train
  proportion: 0.10
python_edu_client_13:
  remote: s3://smollm-corpus/shared/python_edu/client_13
  local: /nfs-share/datasets/photon/dataset_cache/smollm-corpus-shared/python_edu/client_13
  split: train
  proportion: 0.10
python_edu_client_14:
  remote: s3://smollm-corpus/shared/python_edu/client_14
  local: /nfs-share/datasets/photon/dataset_cache/smollm-corpus-shared/python_edu/client_14
  split: train
  proportion: 0.10
python_edu_client_15:
  remote: s3://smollm-corpus/shared/python_edu/client_15
  local: /nfs-share/datasets/photon/dataset_cache/smollm-corpus-shared/python_edu/client_15
  split: train
  proportion: 0.10
